### Get repositories
GET http://localhost:3000/repositories
Accept: application/json

### Get repo by id
GET http://localhost:3000/repositories/2

### Create a repo
POST http://localhost:3000/repositories
Content-Type: application/json

{
  "name": "open-ai-login",
  "idTribe": 2
}

### Delete a repo
DELETE http://localhost:3000/repositories/1
